M48
; DRILL file {KiCad (6.0.7)} date Fri Sep  2 23:16:05 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-02T23:16:05-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X3.5Y-4.4894
X4.7895Y-2.2659
X5.8339Y-4.1493
X7.6535Y-2.2659
X7.6535Y-5.0299
T2
X6.6351Y-2.2755
X6.8604Y-2.2905
X7.0852Y-2.3091
T0
M30
